### ISSUE TITLE
繰り返しフィールド内でCode Editorが使えない

### ISSUE THREAD

**Issue by ryouta-igarashi** [tarosky/tscf#4]
繰り返しフィールド内でCode Editorを選択するとエディターの無い項目が出てくるだけで入力が不可能です。

**Comment by mayukojpn** [comment]
@ryouta-igarashi 
一度投稿を保存すると入力可能になります。
以下のフィールドで同じ現象が起きてます。

- [ ] 日時
- [ ] 日付
- [ ] Code Editor

**Comment by mayukojpn** [comment]
@ryouta-igarashi 修正されてるか確認おねがいします！

**Comment by ryouta-igarashi** [comment]
@mayukojpn 変わらずに問題は起きています。

**Comment by mayukojpn** [comment]
ビルドしましたか？
あと最新のJS読み込んでますか？

**Comment by ryouta-igarashi** [comment]
@mayukojpn 
シークレットウィンドウで試したところ上手くいってるのを確認できましたので完了とさせていただきます。

**Comment by mayukojpn** [comment]
@ryouta-igarashi 
はい。キャッシュクリアしてくださいませ。
