### ISSUE TITLE
カスタムフィールドの表示先として特定の投稿、固定ページを条件指定できるようにしたい

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [tarosky/tscf#8]
管理画面の設定ファイルエディターにて、
現行ではカスタムフィールドの表示先に投稿タイプを指定することができるが、
それに加えて特定の投稿・固定ページを条件指定できる機能を追加したい。

**Comment by fumikito** [comment]
なんかこの機能作った気がしますね。

**Comment by fumikito** [comment]
@ko31 フィルターが存在していました。
汎用的な機能として持たせるべきか、それともフィルターですべきかはサイト次第という感じですかね。
https://github.com/tarosky/tscf/blob/54b25cf7970eb4ed712016e087fce1293e42e68a/src/Tarosky/TSCF/Utility/Parser.php#L207-L235

**Comment by ko31** [comment]
@fumikito そのフィルターの存在に気付いていませんでした・・・。
ひとまずこちらで対応してみたいと思います。どうもありがとうございます！

**Comment by atsufumiyoshikawa** [comment]
こちら閉じます
